"""Add SocialPostQueue table

Revision ID: ddc0abf7a52f
Revises: d708d9ad9836
Create Date: 2026-05-05 17:13:43.379655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc0abf7a52f'
down_revision: Union[str, None] = 'd708d9ad9836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_post_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('media_file_id', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.drop_column('is_fake')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fake', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))

    op.drop_table('social_post_queue')
    # ### end Alembic commands ###
